import = [
  # uncomment the flavour you want below:
    #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
    "~/.config/alacritty/catppuccin-macchiato.toml"
    # "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true
[window]
padding = { x = 4, y = 4}
dynamic_padding = true
decorations = "None"
opacity = 0.95
[font]
normal = {family = "DankMono Nerd Font", style = "Regular"}
bold = {family = "DankMono Nerd Font", style = "Bold"}
italic = {family = "DankMono Nerd Font", style = "Italic"}
size = 18.0
